//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persons.Directory.Application.Resources.US {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persons.Directory.Application.Resources.US.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one phone number must be provided.
        /// </summary>
        public static string AtLeastOnePhoneNumberMustBeProvided {
            get {
                return ResourceManager.GetString("AtLeastOnePhoneNumberMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is required..
        /// </summary>
        public static string BirthDateIsRequired {
            get {
                return ResourceManager.GetString("BirthDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete related person failed..
        /// </summary>
        public static string DeleteRelatedPersonFailed {
            get {
                return ResourceManager.GetString("DeleteRelatedPersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size is too large. Maximum file size is 2MB.
        /// </summary>
        public static string FileSizeIsTooLarge {
            get {
                return ResourceManager.GetString("FileSizeIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name should not contain both English and Georgian alphabets..
        /// </summary>
        public static string FirstNameInvalidAlphabets {
            get {
                return ResourceManager.GetString("FirstNameInvalidAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name length should be between 2 and 50 characters..
        /// </summary>
        public static string FirstNameInvalidLength {
            get {
                return ResourceManager.GetString("FirstNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender should be either Male or Female..
        /// </summary>
        public static string GenderInvalidValue {
            get {
                return ResourceManager.GetString("GenderInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type. Only JPG and PNG files are allowed..
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should not contain both English and Georgian alphabets..
        /// </summary>
        public static string LastNameInvalidAlphabets {
            get {
                return ResourceManager.GetString("LastNameInvalidAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name length should be between 2 and 50 characters..
        /// </summary>
        public static string LastNameInvalidLenght {
            get {
                return ResourceManager.GetString("LastNameInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file is selected.
        /// </summary>
        public static string NoFileIsSelected {
            get {
                return ResourceManager.GetString("NoFileIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number length should be between 4 and 50 characters..
        /// </summary>
        public static string NumberInvalidLenth {
            get {
                return ResourceManager.GetString("NumberInvalidLenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberType should be either Mobile, Office or Home..
        /// </summary>
        public static string NumberInvalidType {
            get {
                return ResourceManager.GetString("NumberInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonalId must contain exactly 11 numeric characters..
        /// </summary>
        public static string PersonalIdMustContainExactly11NumericCharacters {
            get {
                return ResourceManager.GetString("PersonalIdMustContainExactly11NumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person must be at least 18 years old to register..
        /// </summary>
        public static string PersonMustBeAtLeast18YearsOldToRegister_ {
            get {
                return ResourceManager.GetString("PersonMustBeAtLeast18YearsOldToRegister.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person not found by Id: {0}.
        /// </summary>
        public static string PersonNotFoundById {
            get {
                return ResourceManager.GetString("PersonNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person with PersonalId: {0} already exists..
        /// </summary>
        public static string PersonWithPersonalIdAlreadyExists_ {
            get {
                return ResourceManager.GetString("PersonWithPersonalIdAlreadyExists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone numbers cannot be null..
        /// </summary>
        public static string PhoneNumbersCannotBeNull {
            get {
                return ResourceManager.GetString("PhoneNumbersCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedPerson not found by Id: {0}.
        /// </summary>
        public static string RelatedPersonNotFoundById {
            get {
                return ResourceManager.GetString("RelatedPersonNotFoundById", resourceCulture);
            }
        }
    }
}
