//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persons.Directory.Application.Resources.GE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persons.Directory.Application.Resources.GE.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მინიმუმ ერთი ტელეფონის ნომერი უნდა იყოს მითითებული..
        /// </summary>
        public static string AtLeastOnePhoneNumberMustBeProvided {
            get {
                return ResourceManager.GetString("AtLeastOnePhoneNumberMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაბადების თარიღი სავალდებულოა..
        /// </summary>
        public static string BirthDateIsRequired {
            get {
                return ResourceManager.GetString("BirthDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პიროვნების წაშლა ვერ მოხერხდა..
        /// </summary>
        public static string DeleteRelatedPersonFailed {
            get {
                return ResourceManager.GetString("DeleteRelatedPersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილის ზომა აჭარბებს დაშვებულს. მაქსიმალური ფაილის ზომა არის: 2MB.
        /// </summary>
        public static string FileSizeIsTooLarge {
            get {
                return ResourceManager.GetString("FileSizeIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი უნდა შეიცავდეს მხოლოდ ქართულ ან ლათინურ ანბანის ასოებს..
        /// </summary>
        public static string FirstNameInvalidAlphabets {
            get {
                return ResourceManager.GetString("FirstNameInvalidAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი უნდა შედგებოდეს მინიმუმ 2 და მაქსიმუმ 50 სიმბოლოსაგან..
        /// </summary>
        public static string FirstNameInvalidLength {
            get {
                return ResourceManager.GetString("FirstNameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელი სავალდებულოა.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სქესის დასაშვები მნიშვნელობები: მდედრობითი ან მამრობითი..
        /// </summary>
        public static string GenderInvalidValue {
            get {
                return ResourceManager.GetString("GenderInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი ფაილის ტიპი. დასაშვები ფაილის ტიპებია: JPG, PNG..
        /// </summary>
        public static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი უნდა შეიცავდეს მხოლოდ ქართულ ან ლათინურ ანბანის ასოებს..
        /// </summary>
        public static string LastNameInvalidAlphabets {
            get {
                return ResourceManager.GetString("LastNameInvalidAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი უნდა შედგებოდეს მინიმუმ 2 და მაქსიმუმ 50 სიმბოლოსაგან..
        /// </summary>
        public static string LastNameInvalidLenght {
            get {
                return ResourceManager.GetString("LastNameInvalidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარი სავალდებულოა..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილი არ არის არჩეული..
        /// </summary>
        public static string NoFileIsSelected {
            get {
                return ResourceManager.GetString("NoFileIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნომერი უნდა შედგებოდეს მინიმუმ 4 და მაქსიმუმ 50 სიმბოლოსაგან..
        /// </summary>
        public static string NumberInvalidLenth {
            get {
                return ResourceManager.GetString("NumberInvalidLenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონის ნომრის დასაშვები მნიშვნელობებია: მობილური, ოფისი, სახლი..
        /// </summary>
        public static string NumberInvalidType {
            get {
                return ResourceManager.GetString("NumberInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პირადი ნომერი უნდა შედგებოდეს მხოლოდ 11 სიმბოლოსაგან..
        /// </summary>
        public static string PersonalIdMustContainExactly11NumericCharacters {
            get {
                return ResourceManager.GetString("PersonalIdMustContainExactly11NumericCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეგისტრაციისთვის პირი უნდა იყოს მინიმუმ 18 წლის..
        /// </summary>
        public static string PersonMustBeAtLeast18YearsOldToRegister_ {
            get {
                return ResourceManager.GetString("PersonMustBeAtLeast18YearsOldToRegister.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნება ვერ მოიძებნა იდენტიფიკატორით: {0}.
        /// </summary>
        public static string PersonNotFoundById {
            get {
                return ResourceManager.GetString("PersonNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიროვნება აღნიშნული პირადი ნომრით: {0} უკვე არსებობს..
        /// </summary>
        public static string PersonWithPersonalIdAlreadyExists_ {
            get {
                return ResourceManager.GetString("PersonWithPersonalIdAlreadyExists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტელეფონის ნომრები სავალდებულოა..
        /// </summary>
        public static string PhoneNumbersCannotBeNull {
            get {
                return ResourceManager.GetString("PhoneNumbersCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პიროვნება ვერ მოიძებნა იდენტიფიკატორით: {0}.
        /// </summary>
        public static string RelatedPersonNotFoundById {
            get {
                return ResourceManager.GetString("RelatedPersonNotFoundById", resourceCulture);
            }
        }
    }
}
